BACKGROUND_COLOR = "#F3F3F3"
PRIMARY_COLOR = "#250001"
WHITE_COLOR = "#FFFFFF"
BLACK_COLOR = "#000000"

ARIAL_FONT = "Arial"
ARIAL_BOLD_FONT = "Arial Bold"
ARIAL_BOLD_FONT_10 = (ARIAL_BOLD_FONT, 10)

STATE_NORMAL = "normal"
STATE_DISABLED = "disabled"

RELIEF_FLAT = "flat"

CURSOR_HAND2 = "HAND2"

ANCHOR_W = "w"
